# nixpacks.toml
[phases.setup]
nixPkgs = ['...', 'stripe-cli','redis']
cmds = ['...','wget -c https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb','sudo apt-get update','sudo apt-get install libappindicator1', 'sudo dpkg -i google-chrome-stable_current_amd64.deb']