# Generated by Django 4.1.5 on 2023-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0002_product_delete_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
