# Generated by Django 4.1.5 on 2023-03-22 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0003_alter_product_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
