# Generated by Django 4.1.5 on 2023-03-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0004_remove_product_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.URLField(default='http://127.0.0.1:8000/'),
            preserve_default=False,
        ),
    ]
