# Generated by Django 4.1.5 on 2023-03-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0009_order_remove_todolist_user_delete_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date_completed',
        ),
    ]
