# Generated by Django 4.1.5 on 2023-03-27 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0010_remove_order_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
