# Generated by Django 4.1.5 on 2023-03-28 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0013_order_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='license_file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
