# Generated by Django 4.1.5 on 2023-03-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0014_alter_order_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='license_file',
            field=models.FileField(blank=True, upload_to='myfiles/'),
        ),
    ]
