# Generated by Django 4.1.5 on 2023-03-29 12:25

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0015_alter_order_license_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_description',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=600),
            preserve_default=False,
        ),
    ]
