# Generated by Django 4.1.5 on 2023-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0016_order_item_description_order_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='revisions_data',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_description',
            field=models.CharField(max_length=1000),
        ),
    ]
