# Generated by Django 4.1.5 on 2023-03-30 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0017_order_revisions_data_alter_order_item_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='complete',
        ),
    ]
