# Generated by Django 4.2 on 2023-04-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlobby', '0020_alter_order_complete_alter_order_license_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='complete',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Delivered', 'Delivered'), ('Completed', 'Completed')], default='In Progress', max_length=20),
        ),
    ]
